//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyGroup.Models.DBFairyGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int AreaID { get; set; }
        public string ProvinceName { get; set; }
        public string DistrictName { get; set; }
        public string SubDistrictName { get; set; }
        public Nullable<int> ZipCode { get; set; }
    }
}
