//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyGroup.Models.DBFairyGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingTypeGroupDetail
    {
        public int BuildingTypeGroupDetailID { get; set; }
        public string BuildingTypeGroupDetailName { get; set; }
        public string BuildingTypeGroupDetailNameEn { get; set; }
        public Nullable<int> SortID { get; set; }
    }
}
