//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyGroup.Models.DBFairyGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingType
    {
        public int BuildingTypeID { get; set; }
        public string BuildingTypeName { get; set; }
        public string BuildingTypeIcon { get; set; }
        public Nullable<bool> isSale { get; set; }
        public Nullable<bool> isRent { get; set; }
        public Nullable<bool> isOptionToBuy { get; set; }
    }
}
