//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyGroup.Models.DBFairyGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingDetail
    {
        public int BuildingDetailID { get; set; }
        public Nullable<int> BuildingGroupDetailID { get; set; }
        public string DetailName { get; set; }
        public string DetailNameEn { get; set; }
        public string DetailDataType { get; set; }
        public string DetailControlType { get; set; }
        public string DetailControlGroup { get; set; }
        public Nullable<bool> isRequired { get; set; }
        public Nullable<int> SortID { get; set; }
    }
}
