//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyGroup.Models.DBFairyGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public int ProfileID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ProfileHeader { get; set; }
        public string ProfileBody { get; set; }
    }
}
