//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyGroup.Models.DBFairyGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostType
    {
        public int PostTypeID { get; set; }
        public string PostTypeName { get; set; }
        public string PostTypeNameEn { get; set; }
    }
}
