//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyGroup.Models.DBFairyGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostBuilding
    {
        public int PostBuildingID { get; set; }
        public Nullable<int> BuildingTypeID { get; set; }
        public Nullable<int> PostTypeID { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> SubDistrictID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DescriptionEn { get; set; }
        public string PostTitle { get; set; }
        public string PostTitleEn { get; set; }
        public Nullable<bool> isOwner { get; set; }
        public string AddressNo { get; set; }
        public string RoadName { get; set; }
        public string LatitudeMap { get; set; }
        public string LongitudeMap { get; set; }
        public string PostStatus { get; set; }
    }
}
