//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairyGroup.Models.DBFairyGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostBuildingImg
    {
        public int PostBuildingImgID { get; set; }
        public int PostBuildingID { get; set; }
        public string PathName { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
